<script lang="ts">
	import * as Card from '$lib/components/ui/card/index.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import { Badge } from '$lib/components/ui/badge/index.js';
	import * as Alert from '$lib/components/ui/alert/index.js';
	import TotpSetupModal from './totp-setup-modal.svelte';
	import TotpDisableModal from './totp-disable-modal.svelte';
	import TotpRecoveryCodesModal from './totp-recovery-codes-modal.svelte';
	import PasskeyRegisterModal from './passkey-register-modal.svelte';
	import PasskeyListItem from './passkey-list-item.svelte';
	import { getSecurityService } from './securityService.svelte';
	import type { TwoFactorStatusResponse, PasskeyResponse } from '$lib/api/types/security';
	import Shield from '@lucide/svelte/icons/shield';
	import ShieldCheck from '@lucide/svelte/icons/shield-check';
	import ShieldAlert from '@lucide/svelte/icons/shield-alert';
	import KeyRound from '@lucide/svelte/icons/key-round';
	import Plus from '@lucide/svelte/icons/plus';
	import RefreshCw from '@lucide/svelte/icons/refresh-cw';

	let {
		initialStatus,
		initialPasskeys
	}: {
		initialStatus?: TwoFactorStatusResponse | null;
		initialPasskeys?: PasskeyResponse[];
	} = $props();

	const securityService = getSecurityService();

	$effect(() => {
		if (initialStatus !== undefined) {
			securityService.status = initialStatus;
		}
	});

	$effect(() => {
		if (initialPasskeys !== undefined) {
			securityService.passkeys = initialPasskeys;
		}
	});

	let showTotpSetupModal = $state(false);
	let showTotpDisableModal = $state(false);
	let showTotpRecoveryCodesModal = $state(false);
	let showPasskeyRegisterModal = $state(false);

	const status = $derived(securityService.status);
	const passkeys = $derived(securityService.passkeys);
	const isTotpEnabled = $derived(Boolean(status?.totp_enabled));
	const recoveryCodesRemaining = $derived(status?.recovery_codes_remaining ?? 0);
	const error = $derived(securityService.error);
</script>

<div class="mx-auto max-w-4xl space-y-6 p-4 sm:p-6">
	{#if error}
		<Alert.Root variant="destructive">
			<Alert.Description>{error}</Alert.Description>
		</Alert.Root>
	{/if}

	<!-- 2FA Status Card -->
	<Card.Root>
		<Card.Header>
			<div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
				<div class="space-y-1">
					<div class="flex items-center gap-2">
						<Shield class="h-5 w-5 text-primary" />
						<Card.Title>Two-Factor Authentication (2FA)</Card.Title>
					</div>
					<Card.Description>
						Enhance your account security with an authenticator app (TOTP) that generates one-time
						verification codes.
					</Card.Description>
				</div>
				<div>
					{#if isTotpEnabled}
						<Badge variant="default" class="bg-green-600 text-white hover:bg-green-600">
							<ShieldCheck class="mr-1 h-3.5 w-3.5" />
							Enabled
						</Badge>
					{:else}
						<Badge variant="secondary">
							<ShieldAlert class="mr-1 h-3.5 w-3.5" />
							Disabled
						</Badge>
					{/if}
				</div>
			</div>
		</Card.Header>

		<Card.Content>
			{#if isTotpEnabled}
				<div class="space-y-4 rounded-lg border bg-muted/20 p-4">
					<div class="flex flex-col gap-1">
						<p class="text-sm font-medium text-foreground">Authenticator App</p>
						<p class="text-xs text-muted-foreground">
							Your account is protected with 6-digit TOTP verification codes upon sign in.
						</p>
					</div>

					<div class="flex items-center justify-between border-t pt-3 text-sm">
						<div>
							<span class="text-xs font-medium text-muted-foreground">Backup recovery codes</span>
							<p class="text-sm font-medium">
								{recoveryCodesRemaining}
								{recoveryCodesRemaining === 1 ? 'code' : 'codes'} remaining
							</p>
						</div>
						<Button variant="outline" size="sm" onclick={() => (showTotpRecoveryCodesModal = true)}>
							<RefreshCw class="mr-1.5 h-3.5 w-3.5" />
							Regenerate codes
						</Button>
					</div>
				</div>
			{:else}
				<div class="space-y-3">
					<p class="text-sm text-muted-foreground">
						When 2FA is enabled, you'll be prompted for a 6-digit one-time passcode generated by
						apps like Google Authenticator, 1Password, Bitwarden, or Apple Passwords whenever you
						sign in.
					</p>
				</div>
			{/if}
		</Card.Content>

		<Card.Footer class="border-t pt-4">
			{#if isTotpEnabled}
				<Button variant="destructive" size="sm" onclick={() => (showTotpDisableModal = true)}>
					Disable 2FA
				</Button>
			{:else}
				<Button variant="default" size="sm" onclick={() => (showTotpSetupModal = true)}>
					Set up 2FA
				</Button>
			{/if}
		</Card.Footer>
	</Card.Root>

	<!-- Passkeys Management Card -->
	<Card.Root>
		<Card.Header>
			<div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
				<div class="space-y-1">
					<div class="flex items-center gap-2">
						<KeyRound class="h-5 w-5 text-primary" />
						<Card.Title>Passkeys</Card.Title>
					</div>
					<Card.Description>
						Passkeys are secure, phishing-resistant credentials stored on your device that allow you
						to sign in using biometrics (Touch ID, Face ID, Windows Hello) or hardware keys.
					</Card.Description>
				</div>
				<Button size="sm" onclick={() => (showPasskeyRegisterModal = true)}>
					<Plus class="mr-1.5 h-4 w-4" />
					Add Passkey
				</Button>
			</div>
		</Card.Header>

		<Card.Content>
			{#if passkeys.length === 0}
				<div
					class="flex flex-col items-center justify-center rounded-lg border border-dashed p-8 text-center"
				>
					<div class="rounded-full bg-muted p-3">
						<KeyRound class="h-6 w-6 text-muted-foreground" />
					</div>
					<h3 class="mt-3 text-sm font-medium">No passkeys registered</h3>
					<p class="mt-1 text-xs text-muted-foreground">
						Add a passkey to sign in effortlessly without typing your password.
					</p>
					<Button
						variant="outline"
						size="sm"
						class="mt-4"
						onclick={() => (showPasskeyRegisterModal = true)}
					>
						<Plus class="mr-1.5 h-3.5 w-3.5" />
						Add your first passkey
					</Button>
				</div>
			{:else}
				<div class="space-y-3">
					{#each passkeys as passkey (passkey.id)}
						<PasskeyListItem {passkey} />
					{/each}
				</div>
			{/if}
		</Card.Content>
	</Card.Root>
</div>

<!-- Modal Dialogs -->
<TotpSetupModal bind:open={showTotpSetupModal} />
<TotpDisableModal bind:open={showTotpDisableModal} />
<TotpRecoveryCodesModal bind:open={showTotpRecoveryCodesModal} />
<PasskeyRegisterModal bind:open={showPasskeyRegisterModal} />
