"""Add integration user id to accounts

Revision ID: 0d99570e56cf
Revises: e58109e60481
Create Date: 2026-03-09 04:51:16.023969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d99570e56cf'
down_revision: Union[str, Sequence[str], None] = 'e58109e60481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('integration_user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'integration_users', ['integration_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')  # type: ignore[arg-type]
    op.drop_column('accounts', 'integration_user_id')
    # ### end Alembic commands ###
