"""add_price_unique_constraint

Revision ID: 0d9b3a153da8
Revises: 7cb8e3038b76
Create Date: 2026-02-25 05:17:38.430466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9b3a153da8'
down_revision: Union[str, Sequence[str], None] = '7cb8e3038b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('price_security_date_unique', 'market_prices', ['security_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('price_security_date_unique', 'market_prices', type_='unique')
    # ### end Alembic commands ###
