"""add summary to security notes

Revision ID: 3909e15d1793
Revises: 3d431f3bae89
Create Date: 2026-09-22 17:53:40.265626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3909e15d1793'
down_revision: Union[str, Sequence[str], None] = '3d431f3bae89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_security_notes', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_security_notes', 'summary')
    # ### end Alembic commands ###
