"""reset schema

Revision ID: 5ab75fd64c79
Revises: 
Create Date: 2026-02-01 02:12:23.195270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab75fd64c79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'country')
    )
    op.create_table('account_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('tax_advantaged', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'country')
    )
    op.create_table('auth_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    op.create_table('integration_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('external_user_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'institution_id', 'external_user_id')
    )
    op.create_table('market_securities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', name='symbol_exchange_unique')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_type_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_type_id'], ['account_types.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['account_institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'institution_id', 'external_id')
    )
    op.create_table('market_prices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=16, scale=8), nullable=False),
    sa.Column('high', sa.DECIMAL(precision=16, scale=8), nullable=False),
    sa.Column('low', sa.DECIMAL(precision=16, scale=8), nullable=False),
    sa.Column('close', sa.DECIMAL(precision=16, scale=8), nullable=False),
    sa.Column('adjusted_close', sa.DECIMAL(precision=16, scale=8), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['market_securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_securities_broker',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('broker_symbol', sa.String(), nullable=False),
    sa.Column('broker_exchange', sa.String(), nullable=False),
    sa.Column('broker_name', sa.String(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('search_results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['market_securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_positions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=16, scale=8), nullable=False),
    sa.Column('average_cost', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'security_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_positions')
    op.drop_table('market_securities_broker')
    op.drop_table('market_prices')
    op.drop_table('accounts')
    op.drop_table('market_securities')
    op.drop_table('integration_users')
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.drop_table('auth_users')
    op.drop_table('account_types')
    op.drop_table('account_institutions')
    # ### end Alembic commands ###
