"""add auth passkeys

Revision ID: 62e7d900926e
Revises: 2a86ac6b46ec
Create Date: 2026-08-25 20:29:30.126871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e7d900926e'
down_revision: Union[str, Sequence[str], None] = '2a86ac6b46ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_passkeys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('transports', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_passkeys_credential_id'), 'auth_passkeys', ['credential_id'], unique=True)
    op.create_index(op.f('ix_auth_passkeys_user_id'), 'auth_passkeys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_passkeys_user_id'), table_name='auth_passkeys')
    op.drop_index(op.f('ix_auth_passkeys_credential_id'), table_name='auth_passkeys')
    op.drop_table('auth_passkeys')
    # ### end Alembic commands ###
