"""Rename tickers to securities

Revision ID: af5f71c37b1d
Revises: 86d6e41b7b07
Create Date: 2025-11-14 18:19:15.354442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af5f71c37b1d'
down_revision: Union[str, Sequence[str], None] = '86d6e41b7b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('external_id', sa.String(), nullable=False))
    op.drop_index(op.f('ix_user_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_user_email'), 'users', ['email'], unique=True)
    op.drop_column('accounts', 'external_id')
    # ### end Alembic commands ###
