"""add market security note summaries

Autogenerate also emitted a `drop_table('huey_tasks')` (and its inverse in
`downgrade`) because the orphaned Huey SQL-storage table exists in the live
dev database but not in the model metadata. That table was already dropped by
migration `673bef7bd9d1_cleanup_schema_drift` and is intentionally not part of
this revision, so those spurious ops were removed by hand.

Revision ID: b8448ae7dc41
Revises: 8c982c520acb
Create Date: 2026-09-22 03:00:21.592274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b8448ae7dc41'
down_revision: Union[str, Sequence[str], None] = '8c982c520acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_security_note_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['market_securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_security_note_summaries')
    # ### end Alembic commands ###
