"""add_market_chart_snapshots

Revision ID: bea77d72aaf1
Revises: 62e7d900926e
Create Date: 2026-08-27 18:50:52.193131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'bea77d72aaf1'
down_revision: Union[str, Sequence[str], None] = '62e7d900926e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_chart_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('drawings', sa.JSON(), nullable=False),
    sa.Column('data_window', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['market_securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_chart_snapshots_security_user_captured', 'market_chart_snapshots', ['security_id', 'user_id', 'captured_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_chart_snapshots_security_user_captured', table_name='market_chart_snapshots')
    op.drop_table('market_chart_snapshots')
    # ### end Alembic commands ###
