"""add source to market price alerts

Revision ID: c2a9f7b17e13
Revises: 65b4bef42c13
Create Date: 2026-08-21 15:27:21.358291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a9f7b17e13'
down_revision: Union[str, Sequence[str], None] = '65b4bef42c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_price_alerts', sa.Column('source', sa.String(), nullable=False, server_default='manual'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_price_alerts', 'source')
    # ### end Alembic commands ###
