"""add email verification models

Revision ID: caedf9ddc2ab
Revises: 091b98c6bb27
Create Date: 2026-03-02 03:52:20.945925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caedf9ddc2ab'
down_revision: Union[str, Sequence[str], None] = '091b98c6bb27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_verification_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_verification_tokens_token'), 'auth_verification_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_auth_verification_tokens_user_id'), 'auth_verification_tokens', ['user_id'], unique=False)
    op.add_column('auth_users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_users', 'is_verified')
    op.drop_index(op.f('ix_auth_verification_tokens_user_id'), table_name='auth_verification_tokens')
    op.drop_index(op.f('ix_auth_verification_tokens_token'), table_name='auth_verification_tokens')
    op.drop_table('auth_verification_tokens')
    # ### end Alembic commands ###
