"""add title to security notes

Revision ID: cdec46de51af
Revises: 4d78820d50bd
Create Date: 2026-04-07 13:34:35.189322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdec46de51af'
down_revision: Union[str, Sequence[str], None] = '4d78820d50bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_security_notes', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_security_notes', 'title')
    # ### end Alembic commands ###
