"""empty message

Revision ID: d78257b03739
Revises: 0d99570e56cf
Create Date: 2026-03-10 04:43:05.734037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78257b03739'
down_revision: Union[str, Sequence[str], None] = '0d99570e56cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_securities_broker', sa.Column('mapped_symbol', sa.String(), nullable=False))
    op.add_column('market_securities_broker', sa.Column('mapped_exchange', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_securities_broker', 'mapped_exchange')
    op.drop_column('market_securities_broker', 'mapped_symbol')
    # ### end Alembic commands ###
