"""add broker_display_name to accounts

Revision ID: e58109e60481
Revises: a69a19f736fa
Create Date: 2026-03-08 01:10:59.019370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e58109e60481'
down_revision: Union[str, Sequence[str], None] = 'a69a19f736fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('broker_display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'broker_display_name')
    # ### end Alembic commands ###
